### ISSUE TITLE
New Release TODOs | Milestone 1.0

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#24]
Hi there!
According to #23 we already have implementation of List Categories but only in reorg-methods brunch
I think that we should create a roadmap/todo of new release.
TODO:

- [x] Structure Reogranization #18 
- [x] Tests Restructure #21 (PR #32)
- [x] QueryBuilder #22 (Added in PR #29 needs review and test it on real sites with many scenarios)
- [x] Problems with create Media #30 (PR #32 )
- [x] Add constructors with required parameters #31  (PR #32)
- [x] Code review and cleanup. Release stabilization

PP to version 1.1:
- Posts revisions https://developer.wordpress.org/rest-api/reference/post-revisions/ 
- Taxonomies https://developer.wordpress.org/rest-api/reference/taxonomies/ 
- Post types https://developer.wordpress.org/rest-api/reference/post-types/ 
- Post statuses https://developer.wordpress.org/rest-api/reference/post-statuses/

**Comment by ThomasPe** [comment]
we can now test V1.0 and see if there are any issues that need to be fixed quickly. I'll create a new branch for new features planned for milestone V1.1
